### ISSUE TITLE
Switching locations of bars?

### ISSUE THREAD

**Issue by Kaori1** [Dyaxler/SpartanUI_Vanilla#4]
Hello I would like to switch the primary bar (the one with 1, 2, 3...ect) with the one below it. How would I go about doing this?

**Comment by Dyaxler** [comment]
The bar locations are hard coded. Just edit SpartanUI.lua and swap the two values. 84 and 34...

![capture](https://cloud.githubusercontent.com/assets/17400948/15433893/2acf4948-1e69-11e6-8bda-d06c73414285.JPG)

**Comment by Kaori1** [comment]
You're the best! Tyvm, I'll try this^^
