### ISSUE TITLE
Not seeing the top bar/moving chatboxes

### ISSUE THREAD

**Issue by spikebrian** [Dyaxler/SpartanUI_Vanilla#5]
I'm not seeing the top bar from the screen shots. I'm in 1080p.
I'm wanting to scale it up a bit, because the action bars are pretty tiny and the chatboxes and party unit frames move.  So I was wondering if its possible to move them.
Thanks

**Comment by Dyaxler** [comment]
Top Bar from the screen shots is Titan Bar not SpartanUI... Titan Bar has been around for more than a decade and I didn't think it needed to be identified.
