### ISSUE TITLE
Rightbackdrop

### ISSUE THREAD

**Issue by Trurb** [Dyaxler/SpartanUI_Vanilla#6]
Hey, dont know if you are still here.

Are there a way to keep the rightbackdrop off all the time?
Even if i take it off, its on at the next login

And do you know/have a nice raid frames that fits this ui :) ?

**Comment by Dyaxler** [comment]
WOW... never noticed. I guess I really goofed up the Saved Variable toggle. I'll fix that.

**Comment by Dyaxler** [comment]
Oh and BTW... SUI doesn't have any "nice raid frames" only party frames which can be switched off during a raid.

Most RAID'ers prefer their own raid frames. The original and most popular raid frames (xperl, grid, ect...) don't have working range, buffs, debuffs check and are almost useless for support classes like healers. The only other two addons I know of in vanilla which have working range checks are Luna and Sraidframes.

**Comment by Dyaxler** [comment]
Fixed in latest release: https://github.com/Dyaxler/SpartanUI_Vanilla/releases/latest
