### ISSUE TITLE
hovering over DOT on enemy frame

### ISSUE THREAD

**Issue by ultra12345** [Dyaxler/SpartanUI_Vanilla#7]
Hovering over DOT on enemy frame causes an error

**Comment by Dyaxler** [comment]
Which DOT? All these work fine...

![image](https://user-images.githubusercontent.com/17400948/33509396-0fd278f2-d6b6-11e7-814e-53665f5976b6.png)

**Comment by ultra12345** [comment]
Ill get you a screenshot in a moment

**Comment by Dyaxler** [comment]
Preferably I'd love to get a full debug stack... if you use something like !ImprovedErrorFrame it'll dump the whole stack so I can trace the code calls to it's source. Might be another addon that is goofing up the target frame.

**Comment by ultra12345** [comment]
This error occurs when i hover over the mark of pain on the rabbit or any other buff or debuff whether its myself or an enemy, if you need further logs let me know how to do create them and ill try to get them for you:

![sui](https://user-images.githubusercontent.com/34174941/33509537-74bf377a-d6fa-11e7-8ddb-ef154a545a3d.png)

**Comment by Dyaxler** [comment]
Yeah, there has to be a conflicting addon... I use a TON of addons myself and I have everything turned on.

![image](https://user-images.githubusercontent.com/17400948/33509836-f019d5b0-d6b9-11e7-9cbc-8cfdcbd1b5ae.png)

**Comment by Dyaxler** [comment]
Line 3020 is a standard function... without a full debug stack I can't say what or why it's complaining.

![image](https://user-images.githubusercontent.com/17400948/33509868-3bb182c0-d6ba-11e7-9004-ef3535068bfb.png)

**Comment by ultra12345** [comment]
how do i go about creating a debug stack?

**Comment by Dyaxler** [comment]
There is a popular addon called: !ImprovedErrorFrame

I got my version from here: http://addons.us.to/addon/improvederrorframe

**Comment by Dyaxler** [comment]
It shows errors like this... instead of the vague one the default UI shows.

![image](https://user-images.githubusercontent.com/17400948/33509942-1d87ed24-d6bb-11e7-99e9-a268feedb246.png)

**Comment by ultra12345** [comment]
Ok i installed it, how do i bring up that queued errors screen you have there, i get the old message in the chat log instead of a pop up

**Comment by ultra12345** [comment]
Oh i found it was a icon on the mini map, this is what i get

Error:  attempt to call method `IsVisible' (a nil value)
File: Interface\AddOns\SpartanUI\SpartanUI.lua
Line: 3020
Count: 9
--------------------------------------------------
Error:  attempt to call method `IsVisible' (a nil value)
File: Interface\AddOns\SpartanUI\SpartanUI.lua
Line: 3077
Count: 2

**Comment by Dyaxler** [comment]
A nil value?!?! Hmmm... there has to be another addon that is changing the target frame. Clearly the frame is visible. I can see the debuff icon in your screen shot.

Can you dump a list of addons you have? Open a CMD Prompt and navigate to your AddOns folder... run this command:

> dir > addons.txt

![image](https://user-images.githubusercontent.com/17400948/33510215-6ebeb7ce-d6be-11e7-8e47-fdef96383069.png)

This will dump a txt output of your directory to a TXT file. Just upload that to this thread. There won't be anything in the file that identifies you in anyway.

**Comment by Dyaxler** [comment]
Here is mine as an example...

[addons.txt](https://github.com/Dyaxler/SpartanUI_Vanilla/files/1523455/addons.txt)

**Comment by ultra12345** [comment]
my install is buried deep in a secondary drive under some folders and sub folder so ill just list my addons here would be easier:

Decursive
Gatherer
Mail
Mobinfo2
Mobinfo2 Database
SaySapped
SilverDragon
SpartanUI
SpartanUI_Vanilla-master
!ImprovedErrorFrame

and all of the Blizzard_ ones

**Comment by Dyaxler** [comment]
**SpartanUI_Vanilla-master** that folder doesn't need to be in there. Nor does **Mobinfo2 Database**

When you download a mod, never extract a zip file directly into your AddOns folder. ;)

I usually extract zip's to my desktop then examine each folder for readme's to see which folders are in fact the actual mod directory. A lot of mods come with optional addons - like SpartanUI and Mobinfo2 to which I included a huge database for it that you can import. Readme in the Mobinfo2 Database folder.

**Comment by Dyaxler** [comment]
SilverDragon shouldn't conflict. I haven't run Decursive in quite a long time. Where did you get these mods?

SilverDragon
SaySapped
Decursive

I can load them into my client and see if I get an error.

**Comment by ultra12345** [comment]
i deleted those folders ill get the download links for those mods:

https://github.com/Zerf/Decursive

https://github.com/Fiskehatt/SaySapped

https://github.com/HarTstaRx/SilverDragon

**Comment by ultra12345** [comment]
https://github.com/shirsig/Mail

https://github.com/jsb/Gatherer

and thats the other two!

**Comment by Dyaxler** [comment]
Found it... the mod "Mail" is causing the error. Not sure why that mod is conflicting but the code in Spartan for enumerating frames is well documented... here is an example:

http://wowprogramming.com/docs/api/EnumerateFrames

It's a carbon copy cookie cutter code snippet found in tons of mods.

I use GMAIL: http://addons.us.to/addon/gmail

CT_MailMod is buggy.

All your other addons are good.

**Comment by ultra12345** [comment]
Amazing! i would never have thought that addon could cause a conflict with SUI, many many thanks Dyaxler superb help from you, truly.
