### ISSUE TITLE
SUI doesnt save settings

### ISSUE THREAD

**Issue by ultra12345** [Dyaxler/SpartanUI_Vanilla#8]
Changing scale doesnt appear to save when i log back in, im seting my scale with the command:

/run SetCVar("useUiScale", 1) SetCVar("uiScale", 1)

when i relog or exit the game it always goes back to default which is super annoying as i have to paste that command every time.

**Comment by Dyaxler** [comment]
What is your monitors resolution?

SUI auto resizes the UIScale (if it's enabled) and the overall size of all the UI graphics automatically to keep it on the screen, centered and not too small or too big.

Reason I'm asking is that I just recently upgraded my monitor to an Acer Predator X34 (3440 x 1440) and had to rewrite the Sui_ResDetect() function to scale with my new monitor. Here is the updated code:

```
-----------------------------------------------------------------------------------------------
--|  Purpose:	Based on user screen ratio, sets the scale automatically.		    |--
-----------------------------------------------------------------------------------------------
function Sui_ResDetect()
	local resolution = ({GetScreenResolutions()})[GetCurrentResolution()]
	local _, _, x, y = string.find(resolution, "(%d+)x(%d+)")
	local ratio = tonumber(x) / tonumber(y)
-- For Standard 16:9 Screens (1920 x 1080 etc.)
	if ratio < 1.8 and GetCVar("useUiScale") == "1" then
		SetCVar("uiScale", "0.74")
		suiData.scale = .80
	elseif ratio < 1.8 and GetCVar("useUiScale") == "0" then
		suiData.scale = .70
-- for Ultrawide 21:9 Screens (2560 x 1080 etc.)
	elseif ratio < 2.38 and GetCVar("useUiScale") == "1" then
		SetCVar("uiScale", "0.84")
		suiData.scale = .90
	elseif ratio < 2.38 and GetCVar("useUiScale") == "0" then
		suiData.scale = .80
-- for 2K Ultrawide 21:9 Screens (3440 x 1440 etc.)
	elseif ratio > 2.38 and GetCVar("useUiScale") == "1" then
		SetCVar("uiScale", "0.70")
		suiData.scale = .80
	elseif ratio > 2.38 and GetCVar("useUiScale") == "0" then
		suiData.scale = .70
	end
	SpartanUI:SetScale(suiData.scale)
	DEFAULT_CHAT_FRAME:AddMessage("SpartanUI Autores Setting - uiScale: "..GetCVar("uiScale").." | suiScale: "..suiData.scale, 0.65, 0.65, 0.65)
end
```

I also had to update some of the UI graphics - made them wider. I'd be more than happy to wrap up what I've done and post a new build. If you find that you don't like these settings you can always disable the "Auto Resize" feature in SUI by using the following command:

```/sui autores off```

It's on by default...

**Comment by ultra12345** [comment]
my native desktop res is 1920 x 1080 im pretty sure i did turn off that function but ill need to double check, my eyes are what they used to be so having everything super small is quite off putting for me!

Thanks for your response ill double check the autores

**Comment by ultra12345** [comment]
ok I just changed the auto res to off, but now i think the UI may be slightly too big, my old command from my OP now no longer works, i can work with the larger scale but im worried party frames wont fit properly here is the image again that im about to post for my DOT error thread, it shows the scale its now set to though thankfully it did save my settings when i exited:

![sui](https://user-images.githubusercontent.com/34174941/33509480-ecc7faf0-d6f9-11e7-88b0-ff565f1fd0ac.png)

**Comment by Dyaxler** [comment]
In that case set the Autores feature back on... in the above code that I posted search SpartanUI.lua for this phrase: 

> -- For Standard 16:9 Screens (1920 x 1080 etc.)

Under the ```elseif ratio < 1.8...```

Edit this line: ```suiData.scale = .70``` and change it to .50 or .60 or .70... find a scale that works best for you.

```
-- For Standard 16:9 Screens (1920 x 1080 etc.)
	if ratio < 1.8 and GetCVar("useUiScale") == "1" then
		SetCVar("uiScale", "0.74")
		suiData.scale = .80
	elseif ratio < 1.8 and GetCVar("useUiScale") == "0" then
		suiData.scale = .70
```

This will persist after each game session.

**Comment by Dyaxler** [comment]
I packaged up a new release that has all the new code in it... so the above section I copied and pasted will be in there too. Not that it applies to your situation but there is a fix in there for some toggle bugs I found.
