### ISSUE TITLE
a nil value

### ISSUE THREAD

**Issue by Meridaw** [Dyaxler/SpartanUI_Vanilla#9]
![sparta](https://user-images.githubusercontent.com/26133646/36521240-13bbfc24-1796-11e8-9236-a06d2fa1a9e8.jpg)

Fresh install on english client, only got Altoholic, Tourguide and SpartanUI installed.
I get the nil value when i log into game, when i try to take a quest, and it also comes back when i mouseover the xp bar.

**Comment by Dyaxler** [comment]
There are two additional check ins that fix this error. The latest official release doesn't contain these fixes. Sorry about that. Just manually download a zip and copy over SpartanUI.lua and Adept.lua and you should be good to go.

![image](https://user-images.githubusercontent.com/17400948/36549848-a9221124-17a8-11e8-8258-c6a97394e6fd.png)

**Comment by Meridaw** [comment]
great

**Comment by Meridaw** [comment]
The addon now feels and look realy good. Do you got any plans for improvements to it, or is it considerd finished?

**Comment by Meridaw** [comment]
I think it would be silly if blizzard keept the same core for the classic re release, the most important thing is the vanilla experience, as long as they keep that i consider it a win. Im clueless to how much work it takes to change things for addons, it all looks pretty complicated to me, so i just say what i feel, then hope for the best, expecting nothing. I Think all you addon artisan crafters are amazing who takes the time to do all this, it`s pretty great. I checked out the new Tomtom+ Tourguide update combined with pfQuest, works realy well with SpartanUI.
